In [9]:
#TF_ENABLE_ONEDNN_OPTS
import os
import shutil

In [7]:
print(os.getenv('TF_ENABLE_ONEDNN_OPTS'))

None


In [8]:
os.environ['TF_ENABLE_ONEDNN_OPT'] = '0'

In [10]:
import tensorflow as tf
tf.__version__

'2.17.0'

In [11]:
import pandas as pd

### Initialization of Tensors

In [12]:
x = 10
print(x)

10


In [13]:
type(x)

int

In [14]:
x = tf.constant(10)
x

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
x = tf.constant(10, shape=(2, 2), dtype=tf.float32)
x

In [15]:
x = tf.constant([10, 20, 30, 40], shape=(2, 2), dtype=tf.float32)
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[10., 20.],
       [30., 40.]], dtype=float32)>

In [16]:
x = tf.constant([10, 20, 30], shape=(1, 3), dtype=tf.float32)
x

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[10., 20., 30.]], dtype=float32)>

In [17]:
x = tf.constant([10, 20, 30], shape=(3, 1), dtype=tf.float32)
x

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[10.],
       [20.],
       [30.]], dtype=float32)>

In [18]:
x = tf.constant([[10, 20, 30], [40, 50, 60]], shape=(3, 2), dtype=tf.float32)
x

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10., 20.],
       [30., 40.],
       [50., 60.]], dtype=float32)>

In [19]:
tf.ones((3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [20]:
tf.zeros((3, 3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [21]:
tf.eye(3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [22]:
tf.range(10)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [23]:
tf.range(start=1, limit=20, delta=3)

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([ 1,  4,  7, 10, 13, 16, 19])>

In [24]:
tf.random.uniform((3,3), minval=0, maxval=3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.58653617, 2.6757238 , 2.7140014 ],
       [0.774127  , 0.32581222, 1.0961115 ],
       [2.4868333 , 0.4741627 , 1.9765749 ]], dtype=float32)>

In [25]:
tf.random.normal((5,5), mean=0, stddev=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 0.84695214,  0.87207985,  1.3665481 , -0.9257516 ,  0.1955513 ],
       [ 1.2032386 ,  0.79294914, -0.81177753,  1.6657053 ,  1.1718646 ],
       [-1.522811  , -0.15453051, -0.01776025, -0.5973158 ,  0.95820445],
       [ 0.1475356 , -0.63961613, -1.1330544 ,  0.24316652,  0.20016952],
       [ 0.7578713 ,  1.287897  ,  1.0694463 , -1.817073  , -0.6871769 ]],
      dtype=float32)>

In [26]:
x = tf.range(10)

In [27]:
x

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [28]:
tf.cast(x, dtype=tf.float32)

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

### Mathematical Operations

In [29]:
x = tf.constant(10)
y = tf.constant(20)

In [30]:
type(x)

tensorflow.python.framework.ops.EagerTensor

In [31]:
x + y

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [32]:
tf.add(x,y)

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [33]:
tf.subtract(x,y)

<tf.Tensor: shape=(), dtype=int32, numpy=-10>

In [34]:
tf.multiply(x, y)

<tf.Tensor: shape=(), dtype=int32, numpy=200>

In [35]:
tf.divide(x, y)

<tf.Tensor: shape=(), dtype=float64, numpy=0.5>

In [36]:
x = tf.random.normal((2, 3))
y = tf.random.normal((3, 4))

In [37]:
tf.matmul(x, y)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 0.60734975,  1.331028  ,  0.9058512 , -0.93683344],
       [-4.84369   ,  1.1972284 , -1.5063652 ,  3.8736303 ]],
      dtype=float32)>

In [38]:
x @ y #Same as above

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 0.60734975,  1.331028  ,  0.9058512 , -0.93683344],
       [-4.84369   ,  1.1972284 , -1.5063652 ,  3.8736303 ]],
      dtype=float32)>

### Index

In [39]:
x = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [40]:
x[2]

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [41]:
x[2:5]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 4, 5])>

In [42]:
x[:]

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])>

In [43]:
x[2:]

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([ 3,  4,  5,  6,  7,  8,  9, 10])>

In [44]:
x[:6]

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6])>

In [45]:
x[::2]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

In [46]:
tf.gather(x, [0, 3, 7])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 8])>

In [47]:
x = tf.constant([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

In [48]:
x[0,:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [49]:
x[0:2, :]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [50]:
x[0, : 1:2]

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([1])>

In [63]:
x[:, 1:3]

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 6],
       [8, 9]])>

In [64]:
x[0:2, 0:2]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5]])>

### Reshaping

In [65]:
x = tf.range(10)

In [66]:
x

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [69]:
tf.reshape(x, (2, 5))

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])>

### Sessions

In [72]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
x = tf.constant(2)
y = tf.constant(3)

add_op = tf.add(x, y, name='Add')
mul_op = tf.multiply(x, y, name='Multiply')
pow_op = tf.pow(add_op, mul_op, name='Power')
some_op = tf.divide(pow_op, add_op, name='Some')

print(add_op, mul_op, pow_op, some_op)

with tf.compat.v1.Session() as session:
    pow_out, some_out = session.run([add_op, some_op])
    
print(add_op, mul_op, pow_out, some_out)



Tensor("Add_2:0", shape=(), dtype=int32) Tensor("Multiply_2:0", shape=(), dtype=int32) Tensor("Power_2:0", shape=(), dtype=int32) Tensor("Some_2:0", shape=(), dtype=float64)
Tensor("Add_2:0", shape=(), dtype=int32) Tensor("Multiply_2:0", shape=(), dtype=int32) 5 3125.0


In [73]:
import numpy as np
tf.compat.v1.disable_eager_execution()
x = tf.compat.v1.placeholder(tf.float32, shape=(2,2))
y = tf.matmul(x, x)

with tf.compat.v1.Session() as session:
    data = np.random.rand(2, 2)
    result = session.run(y, feed_dict={x: data})
    print(data)
    print(result)

[[0.60324793 0.42199041]
 [0.56928314 0.82759255]]
[[0.6041401  0.603801  ]
 [0.8145534  0.92514145]]


### Keras

In [ ]:

from keras.models import Sequential

In [ ]:
%pip install keras

In [ ]:
from keras.layers import Dense, Activation, Dropout

In [ ]:
num_classes = 3

In [ ]:
model = Sequential()
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(num_classes, activation='softmax'))